### ISSUE TITLE
Issue with contrast color on background text

### ISSUE THREAD

**Issue by thebuilder** [xdrop/night-owl-jetbrains#20] opened 2018-11-12 21:43 UTC
Not sure what the correct name for these labels are, but the dark text is nearly unreadable.
The text it's used for is not critical information, but it would be nice to actually be able to see it. :)

<img width="691" alt="skaermbillede 2018-11-12 kl 22 36 35" src="https://user-images.githubusercontent.com/3764345/48376531-7de96f00-e6cb-11e8-8ec4-8b79c463b5ab.png">
<img width="663" alt="skaermbillede 2018-11-12 kl 22 36 15" src="https://user-images.githubusercontent.com/3764345/48376532-7de96f00-e6cb-11e8-8243-af79e8d446cd.png">

**Comment by thebuilder** [comment] 2018-11-21 13:11
This seems to be solved in the new Webstorm 2018.3 release. 🤔
![skaermbillede 2018-11-21 kl 14 10 32](https://user-images.githubusercontent.com/3764345/48843403-3c298a00-ed97-11e8-9b51-6978d11eac2c.png)

**Comment by xdrop** [comment] 2019-02-01 11:09
Closing as can't reproduce. If issue still persists, please raise again.

**Closed as completed by xdrop** 2019-02-01 11:09 UTC
Labels: bug
